export enum SideBarEnumForWorker {
    GET_WORKER_ACCEPTED_JOB,
    GET_WORKER_LEFT_JOB_FOR_ACCEPT_JOB,
    GET_WORKER_LEFT_JOB_FOR_APPLY_JOB,
    // GET_WORKER_ACCEPTED_COMPLETED_CANCELLED_JOB
    GET_WORKER_COMPLETED_CANCELLED_JOB,
    GET_WORKER_COMPLETED_APPLIED_OFFERED_ACCEPTED_JOB
}