export enum SideBarEnumForSubContractor {
  COMMON,
  BIDDED_FAVOURITE_GOT_INVITATIONS,
  RATING_AND_REVIEW,
  DUMMY,
  BID_QUOTATION,
  ACCEPT_REJECT_PROJECT,
  OFFERED_ACCEPTED,
  PROJECT_LIST,
  OFFERD_ACCEPTED_APPLIED,
}